const keywords = {

  'EN': {
    'return': 'Return',
    'volatility': 'Volatility',
    'avg_return': 'Average daily return',
    'avg_volatility': 'Average daily volatility',
    'overall': 'Overall',
    'risk': 'Risk',
    'name': 'Name',
    'more': 'more',
    'less': 'less',
    'inception_date': 'Inception date',
    'desp': 'Description',
    'days': ' days',
    'month': ' month',
    'year': ' year',
    'radar': 'Radar',
    'table': 'Table',
    'allocation': 'Allocation',
    'sectors': 'Sectors',
    'aggregation': 'Aggregation',
    'sharpe_ratio': 'Sharpe Ratio',
    'max_drawdown':'Max Drawdown',
    'alpha':'Alpha',
    'beta':'beta',
    'publisher': 'Publisher',
    'num_of_stks': '# of Stocks',
    'headline_index': 'Λ Portfolio & Strategy',
    'sort': 'Sort',
    'local': 'Local',
    'published': 'Published',
    'create':'Create',
    'holdings': 'Holdings',
    'key_ratios': 'Key Ratios',
    'historical_data': 'Historical Data',
    'control_panel': 'Control Panel',
    'summary': 'Summary',
    'inception': 'Inception',
    'last_update': 'last_update',
    'latest_change': 'real time',
    'since_creation': 'inception'

  },
  'CH': {
    'return': '累计回报率',
    'volatility': '累计波动率',
    'avg_return': '日均回报率',
    'avg_volatility': '均日波动率',
    'overall': '综合',
    'risk': '风险',
    'name': '名称',
    'more': '展开',
    'less': '收起',
    'inception_date': '创建日',
    'desp': '策略说明',
    'days': '日',
    'month': '个月',
    'year': '年',
    'radar': '综合评估',
    'table': '核心指标',
    'allocation': '个股占比',
    'sectors': '板块占比',
    'aggregation': '投资组合',
    'sharpe_ratio': '夏普率',
    'max_drawdown': '最大回撤',
    'alpha': '阿尔法系数',
    'beta': '贝塔系数',
    'publisher': '发布者',
    'num_of_stks': '个股数',
    'headline_index': 'Λ 股票组合推荐',
    'sort': '排序',
    'local': '自选股组合',
    'published': '投资策略精选',
    'create': '创建新组合',
    'holdings': '持股信息',
    'key_ratios':'量化指标',
    'historical_data':'历史回看',
    'control_panel':'控制面板',
    'summary': '概要',
    'inception': '创建日',
    'last_update': '上次更新',
    'latest_change': '最新涨跌幅',
    'since_creation': '自创建日'
  }
};


module.exports = keywords;
